### ISSUE TITLE
unmaskAsNumber not working

### ISSUE THREAD

**Issue by wiltonlcsj** [kartik-v/yii2-number#8]
Since version 1.0.2 properties unmaskAsNumber and autoUnmask is not working at all. If you put them as false, it's still making a conversion for standard float mask after blur, until version 1.0.1 working as properly.

Config Ex.:
`'maskedInputOptions' => [`
       `'groupSeparator' => '.',`
        `'radixPoint' => ',',`
        `'autoUnmask' => false,`
        `'unmaskAsNumber' => false,`
`],`

Input:
![image](https://user-images.githubusercontent.com/20567057/43535683-08a5aa46-9591-11e8-99d7-159419cbb3f1.png)

Expect behavior:
![image](https://user-images.githubusercontent.com/20567057/43535709-161dc4a6-9591-11e8-961e-331d184ed91c.png)

Obtained behavior:
![image](https://user-images.githubusercontent.com/20567057/43535755-3223e89c-9591-11e8-93c5-e0493d6dea58.png)

**Comment by kartik-v** [comment]
Note this change as been done as per issue #4 and is intentional as per the need why this widget is created.

The internal hidden input will always save a pure number (without any masks - irrespective of other settings). This widget is intended to do that - i,e, always both READ as well as WRITE (save/store) a pure number data and only convert the display on the frontend to the masked number format.

For your case where you need to both READ and WRITE only masked data then you can directly use the `yii\widgets\InputMask` widget.

Having said that, I will try to enhance an option for model based ActiveField inputs to have another model attribute (i.e. a property `NumberControl::displayAttribute`) which can be used to READ and WRITE masked data to the model attribute.
